//>>built
(function(v,s){var p,F=function(){},oa=function(a){for(var b in a)return 0;return 1},X={}.toString,z=function(a){return"[object Function]"==X.call(a)},G=function(a){return"[object String]"==X.call(a)},Y=function(a){return"[object Array]"==X.call(a)},r=function(a,b){if(a)for(var c=0;c<a.length;)b(a[c++])},l=function(a,b){for(var c in b)a[c]=b[c];return a},A=function(a,b){return l(Error(a),{src:"dojoLoader",info:b})},Ha=1,pa=function(){return"_"+Ha++},e=function(a,b,c){return qa(a,b,c,0,e)},H=this,
t=H.document,Ia=t&&t.createElement("DiV"),m=e.has=function(a){return z(x[a])?x[a]=x[a](H,t,Ia):x[a]},x=m.cache=s.hasCache;m.add=function(a,b,c,d){(void 0===x[a]||d)&&(x[a]=b);return c&&m(a)};m.add("host-webworker","undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope);m("host-webworker")&&(l(s.hasCache,{"host-browser":0,dom:0,"dojo-dom-ready-api":0,"dojo-sniff":0,"dojo-inject-api":1,"host-webworker":1}),s.loaderPatch={injectUrl:function(a,b){try{importScripts(a),b()}catch(c){console.error(c)}}});
for(var q in v.has)m.add(q,v.has[q],0,1);e.async=1;var Ja=new Function("return eval(arguments[0]);");e.eval=function(a,b){return Ja(a+"\r\n//# sourceURL\x3d"+b)};var Z={},B=e.signal=function(a,b){var c=Z[a];r(c&&c.slice(0),function(a){a.apply(null,Y(b)?b:[b])})},L=e.on=function(a,b){var c=Z[a]||(Z[a]=[]);c.push(b);return{remove:function(){for(var a=0;a<c.length;a++)if(c[a]===b){c.splice(a,1);break}}}},ra=[],Ka={},sa=[],$={},ta=e.map={},M=[],n={},aa="",C={},N={};q={};var D=0,P=function(a){var b,c,
d,f;for(b in N)c=N[b],(d=b.match(/^url\:(.+)/))?C["url:"+ua(d[1],a)]=c:"*now"==b?f=c:"*noref"!=b&&(d=O(b,a,!0),C[d.mid]=C["url:"+d.url]=c);f&&f(ba(a));N={}},va=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},ca=function(a,b){b.splice(0,b.length);for(var c in a)b.push([c,a[c],new RegExp("^"+va(c)+"(/|$)"),c.length]);b.sort(function(a,b){return b[3]-a[3]});return b},La=function(a,b){r(a,function(a){b.push([G(a[0])?new RegExp("^"+va(a[0])+"$"):a[0],a[1]])})},wa=
function(a){var b=a.name;b||(b=a,a={name:b});a=l({main:"main"},a);a.location=a.location?a.location:b;a.packageMap&&(ta[b]=a.packageMap);a.main.indexOf("./")||(a.main=a.main.substring(2));$[b]=a},xa=[],I=function(a,b,c){for(var d in a){"waitSeconds"==d&&(e.waitms=1E3*(a[d]||0));"cacheBust"==d&&(aa=a[d]?G(a[d])?a[d]:(new Date).getTime()+"":"");if("baseUrl"==d||"combo"==d)e[d]=a[d];a[d]!==x&&(e.rawConfig[d]=a[d],"has"!=d&&m.add("config-"+d,a[d],0,b))}e.baseUrl||(e.baseUrl="./");/\/$/.test(e.baseUrl)||
(e.baseUrl+="/");for(d in a.has)m.add(d,a.has[d],0,b);r(a.packages,wa);for(var f in a.packagePaths)r(a.packagePaths[f],function(a){var b=f+"/"+a;G(a)&&(a={name:a});a.location=b;wa(a)});ca(l(ta,a.map),M);r(M,function(a){a[1]=ca(a[1],[]);"*"==a[0]&&(M.star=a)});ca(l(Ka,a.paths),sa);La(a.aliases,ra);if(b)xa.push({config:a.config});else for(d in a.config)b=y(d,c),b.config=l(b.config||{},a.config[d]);a.cache&&(P(),N=a.cache,a.cache["*noref"]&&P());B("config",[a,e.rawConfig])},w=t.getElementsByTagName("script");
p=0;for(var k,E,J;p<w.length;)if(k=w[p++],(E=k.getAttribute("src"))&&(J=E.match(/(((.*)\/)|^)dojo\.js(\W|$)/i))&&(E=J[3]||"",s.baseUrl=s.baseUrl||E,D=k),E=k.getAttribute("data-dojo-config")||k.getAttribute("djConfig"))q=e.eval("({ "+E+" })","data-dojo-config"),D=k;e.rawConfig={};I(s,1);I(v,1);I(q,1);var Q=function(a){da(function(){r(a.deps,za)})},qa=function(a,b,c,d,f){var g;if(G(a)){if((g=y(a,d,!0))&&g.executed)return g.result;throw A("undefinedModule",a);}Y(a)||(I(a,0,d),a=b,b=c);if(Y(a))if(a.length){c=
"require*"+pa();for(var ya,m=[],k=0;k<a.length;)ya=a[k++],m.push(y(ya,d));g=l(R("",c,0,""),{injected:2,deps:m,def:b||F,require:d?d.require:e,gc:1});n[g.mid]=g;Q(g);var r=K&&0!="sync";da(function(){ea(g,r)});g.executed||u.push(g);S()}else b&&b();return f},ba=function(a){if(!a)return e;var b=a.require;b||(b=function(c,d,f){return qa(c,d,f,a,b)},a.require=l(b,e),b.module=a,b.toUrl=function(b){return ua(b,a)},b.toAbsMid=function(b){return fa(b,a)});return b},u=[],T=[],h={},Na=function(a){a.injected=1;
h[a.mid]=1;a.url&&(h[a.url]=a.pack||1);Ma()},U=function(a){a.injected=2;delete h[a.mid];a.url&&delete h[a.url];oa(h)&&Oa()},Pa=e.idle=function(){return!T.length&&oa(h)&&!u.length&&!K},ga=function(a,b){if(b)for(var c=0;c<b.length;c++)if(b[c][2].test(a))return b[c];return 0},Aa=function(a){var b=[],c,d;for(a=a.replace(/\\/g,"/").split("/");a.length;)c=a.shift(),".."==c&&b.length&&".."!=d?(b.pop(),d=b[b.length-1]):"."!=c&&b.push(d=c);return b.join("/")},R=function(a,b,c,d){return{pid:a,mid:b,pack:c,
url:d,executed:0,def:0}},Ba=function(a,b,c,d,f,g,e,l,m){var k,n,h,p;p=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||p&&!b)return R(0,a,0,a);a=Aa(p?b.mid+"/../"+a:a);if(/^\./.test(a))throw A("irrationalPath",a);b&&(h=ga(b.mid,g));(h=(h=h||g.star)&&ga(a,h[1]))&&(a=h[1]+a.substring(h[3]));b=(J=a.match(/^([^\/]+)(\/(.+))?$/))?J[1]:"";(k=c[b])?a=b+"/"+(n=J[3]||k.main):b="";var q=0;r(l,function(b){var c=a.match(b[0]);c&&0<c.length&&(q=z(b[1])?a.replace(b[0],b[1]):b[1])});if(q)return Ba(q,0,c,d,f,g,e,l,
m);if(c=d[a])return m?R(c.pid,c.mid,c.pack,c.url):d[a];d=(h=ga(a,e))?h[1]+a.substring(h[3]):b?k.location+"/"+n:a;/(^\/)|(\:)/.test(d)||(d=f+d);return R(b,a,k,Aa(d+".js"))},O=function(a,b,c){return Ba(a,b,$,n,e.baseUrl,c?[]:M,c?[]:sa,c?[]:ra)},Ca=function(a,b,c){return a.normalize?a.normalize(b,function(a){return fa(a,c)}):fa(b,c)},Da=0,y=function(a,b,c){var d,f;(d=a.match(/^(.+?)\!(.*)$/))?(f=y(d[1],b,c),5!==f.executed||f.load||ha(f),f.load?(d=Ca(f,d[2],b),a=f.mid+"!"+(f.dynamic?++Da+"!":"")+d):(d=
d[2],a=f.mid+"!"+ ++Da+"!waitingForPlugin"),a={plugin:f,mid:a,req:ba(b),prid:d}):a=O(a,b);return n[a.mid]||!c&&(n[a.mid]=a)},fa=e.toAbsMid=function(a,b){return O(a,b).mid},ua=e.toUrl=function(a,b){var c=O(a+"/x",b),d=c.url;return Ea(0===c.pid?a:d.substring(0,d.length-5))},Fa={injected:2,executed:5,def:3,result:3},w=function(a){return n[a]=l({mid:a},Fa)},Qa=w("require"),Ra=w("exports"),Sa=w("module"),V={},ia=0,ha=function(a){var b=a.result;a.dynamic=b.dynamic;a.normalize=b.normalize;a.load=b.load;
return a},Ta=function(a){var b={};r(a.loadQ,function(c){var d=Ca(a,c.prid,c.req.module),e=a.dynamic?c.mid.replace(/waitingForPlugin$/,d):a.mid+"!"+d,d=l(l({},c),{mid:e,prid:d,injected:0});n[e]||Ga(n[e]=d);b[c.mid]=n[e];U(c);delete n[c.mid]});a.loadQ=0;var c=function(a){for(var c=a.deps||[],d=0;d<c.length;d++)(a=b[c[d].mid])&&(c[d]=a)},d;for(d in n)c(n[d]);r(u,c)},ja=function(a){e.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=ia++;a.loadQ&&(ha(a),Ta(a));for(p=0;p<u.length;)u[p]===a?u.splice(p,
1):p++;/^require\*/.test(a.mid)&&delete n[a.mid]},Ua=[],ea=function(a,b){if(4===a.executed)return e.trace("loader-circular-dependency",[Ua.concat(a.mid).join("-\x3e")]),!a.def||b?V:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return V;var c=a.mid,d=a.deps||[],f,g=[],h=0;for(a.executed=4;f=d[h++];){f=f===Qa?ba(a):f===Ra?a.cjs.exports:f===Sa?a.cjs:ea(f,b);if(f===V)return a.executed=0,e.trace("loader-exec-module",["abort",c]),V;g.push(f)}e.trace("loader-run-factory",[a.mid]);c=a.def;g=z(c)?c.apply(null,
g):c;a.result=void 0===g&&a.cjs?a.cjs.exports:g;ja(a)}return a.result},K=0,da=function(a){try{K++,a()}finally{K--}Pa()&&B("idle",[])},S=function(){K||da(function(){for(var a,b,c=0;c<u.length;)a=ia,b=u[c],ea(b),a!=ia?c=0:c++})},Ea="function"==typeof v.fixupUrl?v.fixupUrl:function(a){a+="";return a+(aa?(/\?/.test(a)?"\x26":"?")+aa:"")},Ga=function(a){var b=a.plugin;5!==b.executed||b.load||ha(b);var c=function(b){a.result=b;U(a);ja(a);S()};b.load?b.load(a.prid,a.req,c):b.loadQ?b.loadQ.push(a):(b.loadQ=
[a],u.unshift(b),za(b))},W=0,ka=0,la=0,Va=function(a,b){la=1;a===W?W.call(null):e.eval(a,b.url);la=0},za=function(a){var b=a.mid,c=a.url;if(!(a.executed||a.injected||h[b]||a.url&&(a.pack&&h[a.url]===a.pack||1==h[a.url])))if(Na(a),a.plugin)Ga(a);else{var d=function(){Wa(a);if(2!==a.injected){if(m("dojo-enforceDefine")){B("error",A("noDefine",a));return}U(a);l(a,Fa);e.trace("loader-define-nonmodule",[a.url])}S()};(W=C[b]||C["url:"+a.url])?(e.trace("loader-inject",["cache",a.mid,c]),Va(W,a),d()):(e.trace("loader-inject",
["script",a.mid,c]),ka=a,e.injectUrl(Ea(c),d,a),ka=0)}},ma=function(a,b,c){e.trace("loader-define-module",[a.mid,b]);if(2===a.injected)return B("error",A("multipleDefine",a)),a;l(a,{deps:b,def:c,cjs:{id:a.mid,uri:a.url,exports:a.result={},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var d=0;b[d];d++)b[d]=y(b[d],a);U(a);z(c)||b.length||(a.result=c,ja(a));return a},Wa=function(a,b){for(var c=[],d,e;T.length;)e=T.shift(),b&&(e[0]=b.shift()),d=e[0]&&y(e[0])||a,c.push([d,
e[1],e[2]]);P(a);r(c,function(a){Q(ma.apply(null,a))})},Oa=F,Ma=F;m.add("ie-event-behavior",t.attachEvent&&"undefined"===typeof Windows&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var na=function(a,b,c,d){if(m("ie-event-behavior"))return a.attachEvent(c,d),function(){a.detachEvent(c,d)};a.addEventListener(b,d,!1);return function(){a.removeEventListener(b,d,!1)}},Xa=na(window,"load","onload",function(){e.pageLoaded=1;"complete"!=t.readyState&&(t.readyState="complete");Xa()}),
w=t.getElementsByTagName("script");for(p=0;!D;)/^dojo/.test((k=w[p++])&&k.type)||(D=k);e.injectUrl=function(a,b,c){c=c.node=t.createElement("script");var d=na(c,"load","onreadystatechange",function(a){a=a||window.event;var c=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(c.readyState))d(),e(),b&&b()}),e=na(c,"error","onerror",function(b){d();e();B("error",A("scriptError",[a,b]))});c.type="text/javascript";c.charset="utf-8";c.src=a;D.parentNode.insertBefore(c,D);return c};e.log=
F;e.trace=F;k=function(a,b,c){var d=arguments.length,f=["require","exports","module"],g=[0,a,b];1==d?g=[0,z(a)?f:[],a]:2==d&&G(a)?g=[a,z(b)?f:[],b]:3==d&&(g=[a,b,c]);e.trace("loader-define",g.slice(0,2));if((d=g[0]&&y(g[0]))&&!h[d.mid])Q(ma(d,g[1],g[2]));else if(!m("ie-event-behavior")||la)T.push(g);else{d=d||ka;if(!d)for(a in h)if((f=n[a])&&f.node&&"interactive"===f.node.readyState){d=f;break}d?(P(d),Q(ma(d,g[1],g[2]))):B("error",A("ieDefineFailed",g[0]));S()}};k.amd={vendor:"dojotoolkit.org"};l(l(e,
s.loaderPatch),v.loaderPatch);L("error",function(a){try{if(console.error(a),a instanceof Error)for(var b in a);}catch(c){}});l(e,{uid:pa,cache:C,packs:$});H.define||(H.define=k,H.require=e,r(xa,function(a){I(a)}),L=q.deps||v.deps||s.deps,q=q.callback||v.callback||s.callback,e.boot=L||q?[L||[],q]:0)})(this.dojoConfig||this.djConfig||this.require||{},{async:1,defaultDuration:100,gfxRenderer:"canvas,svg,vml,silverlight",hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,
"dojo-has-api":1,"dojo-loader":1,dom:1,"host-browser":1},noGlobals:1,packages:[{location:"../dojox",name:"dojox"},{location:"../tm1web",name:"tm1web"},{location:"../dijit",name:"dijit"},{location:".",name:"dojo"},{location:"../com",name:"com"}],parseOnLoad:0});require.boot&&require.apply(null,require.boot);
//# sourceMappingURL=dojo.js.map